function FIFF = mymne_define_constants

% Taken from mne/io/constants.py.

% Gets the original set of constants.
FIFF = fiff_define_constants;


% Adds the extra constants.
FIFF.FIFFB_BEM               = 310;
FIFF.FIFFB_BEM_SURF          = 311;

FIFF.FIFFB_MNE_EPOCHS        = 373;
FIFF.FIFFB_MNE_ICA           = 374;

FIFF.FIFF_SUBJ_HIS_ID        = 410;

FIFF.FIFF_BEM_SURF_ID        = 3101;
FIFF.FIFF_BEM_SURF_NAME      = 3102;
FIFF.FIFF_BEM_SURF_NNODE     = 3103;
FIFF.FIFF_BEM_SURF_NTRI      = 3104;
FIFF.FIFF_BEM_SURF_NODES     = 3105;
FIFF.FIFF_BEM_SURF_TRIANGLES = 3106;
FIFF.FIFF_BEM_SURF_NORMALS   = 3107;

FIFF.FIFF_BEM_POT_SOLUTION   = 3110;
FIFF.FIFF_BEM_APPROX         = 3111;
FIFF.FIFF_BEM_COORD_FRAME    = 3112;
FIFF.FIFF_BEM_SIGMA          = 3113;

FIFF.FIFFV_BEM_APPROX_CONST  = 1;
FIFF.FIFFV_BEM_APPROX_LINEAR = 2;

FIFF.FIFFV_ASPECT_AVERAGE       = 100;
FIFF.FIFFV_ASPECT_STD_ERR       = 101;
FIFF.FIFFV_ASPECT_SINGLE        = 102;
FIFF.FIFFV_ASPECT_SUBAVERAGE    = 103;
FIFF.FIFFV_ASPECT_ALTAVERAGE    = 104;
FIFF.FIFFV_ASPECT_SAMPLE        = 105;
FIFF.FIFFV_ASPECT_POWER_DENSITY = 106;
FIFF.FIFFV_ASPECT_DIPOLE_WAVE   = 200;

FIFF.FWD_BEM_UNKNOWN         = -1;
FIFF.FWD_BEM_CONSTANT_COLL   = 1;
FIFF.FWD_BEM_LINEAR_COLL     = 2;

FIFF.FWD_BEM_IP_APPROACH_LIMIT  = 0.1;


FIFF.FIFF_SUBJ_ID          = 400;
FIFF.FIFF_SUBJ_FIRST_NAME  = 401;
FIFF.FIFF_SUBJ_MIDDLE_NAME = 402;
FIFF.FIFF_SUBJ_LAST_NAME   = 403;
FIFF.FIFF_SUBJ_BIRTH_DAY   = 404;
FIFF.FIFF_SUBJ_SEX         = 405;
FIFF.FIFF_SUBJ_HAND        = 406;
FIFF.FIFF_SUBJ_WEIGHT      = 407;
FIFF.FIFF_SUBJ_HEIGHT      = 408;
FIFF.FIFF_SUBJ_COMMENT     = 409;
FIFF.FIFF_SUBJ_HIS_ID      = 410;

FIFF.FIFF_PROJ_ID      = 500;
FIFF.FIFF_PROJ_NAME    = 501;
FIFF.FIFF_PROJ_AIM     = 502;
FIFF.FIFF_PROJ_PERSONS = 503;
FIFF.FIFF_PROJ_COMMENT = 504;



FIFF.FIFF_HPI_SLOPES  = 215;
FIFF.FIFF_HPI_NCOIL   = 216;
FIFF.FIFF_HPI_COIL_FREQ          = 236;
FIFF.FIFF_HPI_COIL_MOMENTS       = 240;
FIFF.FIFF_HPI_FIT_GOODNESS       = 241;
FIFF.FIFF_HPI_FIT_ACCEPT         = 242;
FIFF.FIFF_HPI_FIT_GOOD_LIMIT     = 243;
FIFF.FIFF_HPI_FIT_DIST_LIMIT     = 244;
FIFF.FIFF_HPI_COIL_NO            = 245;
FIFF.FIFF_HPI_COILS_USED         = 246;
FIFF.FIFF_HPI_DIGITIZATION_ORDER = 247;
FIFF.FIFF_HPI_BAD_CHS            = 225;
FIFF.FIFF_HPI_CORR_COEFF         = 226;

FIFF.FIFF_REF_EVENT              = 211;
FIFF.FIFF_EXPERIMENTER           = 212;
FIFF.FIFF_CH_POS                 = 214;
FIFF.FIFF_REQ_EVENT              = 217;
FIFF.FIFF_REQ_LIMIT              = 218;
FIFF.FIFF_BAD_CHS                = 220;
FIFF.FIFF_ARTEF_REMOVAL          = 221;
FIFF.FIFF_CH_CALS                = 224;
FIFF.FIFF_EVENT_COMMENT          = 227;
FIFF.FIFF_NO_SAMPLES             = 228;
FIFF.FIFF_FIRST_TIME             = 229;
FIFF.FIFF_LINE_FREQ              = 235;
FIFF.FIFF_GANTRY_ANGLE           = 282;

FIFF.FIFFB_HPI_MEAS           = 108;
FIFF.FIFFB_HPI_RESULT         = 109;
FIFF.FIFFB_HPI_COIL           = 110;


FIFF.FIFF_REF_ROLE        = 115;
FIFF.FIFF_REF_FILE_ID     = 116;
FIFF.FIFF_REF_FILE_NUM    = 117;
FIFF.FIFF_REF_FILE_NAME   = 118;

FIFF.FIFFV_ROLE_PREV_FILE = 1;
FIFF.FIFFV_ROLE_NEXT_FILE = 2;


FIFF.FIFF_CREATOR         = 113;

FIFF.FIFFB_DATA_CORRECTION    = 500;
FIFF.FIFFB_CHANNEL_DECOUPLER  = 501;
FIFF.FIFFB_SSS_INFO           = 502;
FIFF.FIFFB_SSS_CAL            = 503;
FIFF.FIFFB_SSS_ST_INFO        = 504;
FIFF.FIFFB_SSS_BASES          = 505;
FIFF.FIFFB_SMARTSHIELD        = 510;

FIFF.FIFF_SSS_FRAME                 = 263;
FIFF.FIFF_SSS_JOB                   = 264;
FIFF.FIFF_SSS_ORIGIN                = 265;
FIFF.FIFF_SSS_ORD_IN                = 266;
FIFF.FIFF_SSS_ORD_OUT               = 267;
FIFF.FIFF_SSS_NMAG                  = 268;
FIFF.FIFF_SSS_COMPONENTS            = 269;
FIFF.FIFF_SSS_CAL_CHANS             = 270;
FIFF.FIFF_SSS_CAL_CORRS             = 271;
FIFF.FIFF_SSS_ST_CORR               = 272;
FIFF.FIFF_SSS_NFREE                 = 278;
FIFF.FIFF_SSS_ST_LENGTH             = 279;
FIFF.FIFF_DECOUPLER_MATRIX          = 800;

FIFF.FIFF_SPHERE_ORIGIN          = 3001;
FIFF.FIFF_SPHERE_RADIUS          = 3002;
FIFF.FIFF_PROJ_ITEM_KIND         = 3411;
FIFF.FIFF_PROJ_ITEM_TIME         = 3412;
FIFF.FIFF_PROJ_ITEM_NVEC         = 3414;
FIFF.FIFF_PROJ_ITEM_VECTORS      = 3415;
FIFF.FIFF_PROJ_ITEM_DEFINITION   = 3416;
FIFF.FIFF_PROJ_ITEM_CH_NAME_LIST = 3417;